portafoliot/authapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profileinfo/', views.profileinfo, name='profileinfo'),
]

portafoliot/contactapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('contact/', views.contact_view, name='contact'),
    path('success/', views.success_message, name='success_message'),
]

portafoliot/portafoliot/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.conf.urls import handler404
from errorapp.views import error_404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='home/', permanent=True)),
    # HomeApp
    path('home/', include('homeapp.urls')),
    # BlogApp
    path('blog/', include('blogapp.urls')),
    # ContactApp
    path('contact/', include('contactapp.urls')),
    # AuthApp
    path('auth/', include('authapp.urls')),
    # ExpensesApp
    path('expenses/', include('expensesapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'errorapp.views.error_404'

portafoliot/contactapp/models.py
from django.db import models

class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return self.name

portafoliot/contactapp/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'message']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'message': forms.Textarea(attrs={'class': 'form-control', 'rows': 4}),
        }

portafoliot/contactapp/views.py
from django.shortcuts import render, redirect
from .forms import ContactForm


def contact_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('success_message')
    else:
        form = ContactForm()
    return render(request, 'contactapp/contact.html', {'form': form})

def success_message(request):
    return render(request, 'contactapp/success.html')

portafoliot/contactapp/templates/contactapp/contact.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Contact{% endblock %}
{% block content %}

<div id="form" class="container mt-6"><br>
    <h1 style="color:burlywood;">Formulario de Contacto</h1><br>
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_name" class="form-label" style="color:burlywood;">Nombre</label>
            {{ form.name }}
        </div>
        <div class="mb-3">
            <label for="id_email" class="form-label" style="color:burlywood;">Dirección Email</label>
            {{ form.email }}
        </div>
        <div class="mb-3">
            <label for="id_message" class="form-label" style="color:burlywood;">Mensaje</label>
            {{ form.message }}
        </div>
        <button type="submit" class="btn btn-dark" style="color:burlywood;">Enviar</button><br>
    </form>
</div>
{% endblock %}

{% block style %}
<style>
    #form {
        width: 40%;
    }

    @media (max-width: 768px) {
        #form {
            width: 90%;
        }
    }
</style>
{% endblock %}

portafoliot/contactapp/templates/contactapp/success.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Success{% endblock %}

{% block content %}
    <div class="container text-center mt-5">
        <h1>¡Mensaje enviado con éxito!</h1>
        <p>Gracias por contactarnos. Nos pondremos en contacto contigo pronto.</p>
    </div>
{% endblock %}
    